@startuml
'https://plantuml.com/class-diagram

hide empty members

class UserService
class UserServiceV2
interface DataFetcher

DataFetcher <|-- UserService
DataFetcher <|-- UserServiceV2
DataFetcher <-- UserServiceV2

@enduml