@startuml
'https://plantuml.com/class-diagram

abstract class ShipFactory
class BalancedShipFactory
class RandomShipFactory

class CargoBasic
class CargoExcel
class Ship

Ship <- ShipFactory

ShipFactory <|-- BalancedShipFactory
ShipFactory <|-- RandomShipFactory

Ship <|-- CargoBasic
Ship <|-- CargoExcel

@enduml