@startuml

hide empty members

Class Translator
Interface Dictionary
Class EnglishToFrenchDictionary
Class EnglishToPortugueseDictionary

Translator --> Dictionary
Dictionary <|.. EnglishToFrenchDictionary
Dictionary <|.. EnglishToPortugueseDictionary

@enduml