@startuml

hide empty members

class WeatherDataFetcher
class WeatherDataFetcherProxy
interface DataFetcher

DataFetcher <|-- WeatherDataFetcherProxy
DataFetcher <|-- WeatherDataFetcher
WeatherDataFetcherProxy -> WeatherDataFetcher

@enduml
